sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - develop
  - staging
  - QA

jobs:
  include:
    - stage: flowz-api-documentation
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t flowz-api-documentation:latest .;
            docker images;
            docker tag flowz-api-documentation:latest $DOCKER_USERNAME_FLOWZ/flowz-api-documentation:latest;
            docker push $DOCKER_USERNAME_FLOWZ/flowz-api-documentation:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz-api-documentation:dev .;
            docker images;
            docker tag flowz-api-documentation:dev $DOCKER_USERNAME/flowz-api-documentation:dev;
            docker push $DOCKER_USERNAME/flowz-api-documentation:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz-api-documentation:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER .;
            docker tag flowz-api-documentation:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/flowz-api-documentation:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag flowz-api-documentation:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/flowz-api-documentation:staging;
            docker images;
            docker push $DOCKER_USERNAME/flowz-api-documentation:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/flowz-api-documentation:staging;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz-api-documentation:qa .;
            docker images;
            docker tag flowz-api-documentation:qa $DOCKER_USERNAME/flowz-api-documentation:qa;
            docker push $DOCKER_USERNAME/flowz-api-documentation:qa;
        fi'
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - acharotariya@officebrain.com
      - mshah@officebrain.com
      - avasani@officebrain.com
    on_success: always
    on_failure: always